config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#home"

  resources :sessions, only: [:create, :destroy]
  resources :static_pages, only: [:home]
  resources :staffs
  resources :polls
  resources :options

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy'

  get 'static_pages_home', to: 'static_pages#home'

  get 'staff_edit', to: 'staffs#edit'
  get 'staff_login', to: 'staffs#login'
  # get 'staff_show', to: 'staffs#show'
  # get 'staff_index', to: 'staffs#index'

  # get 'poll_new', to: 'polls#new'
  # post 'poll_create', to: 'polls#create'
  # get 'poll_show', to: 'polls#show'
  # get 'poll_update', to: 'polls#update'
  # get 'polls_index', to: 'polls#index'
  get 'polls_destroy', to: 'polls#destroy'

  get 'update_key_person_staff', to:'staffs#update_key_person'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :staff_polls
  has_many :option

  def get_list_staff_voted
    list_staff = Array.new
    list_staff_poll = StaffPoll.where(:poll_id => self.id)
    puts "#{list_staff_poll.size}"
    list_staff_poll.each do |staff_poll|
      staff_id = staff_poll.staff_id
      list_staff.push(Staff.find(staff_id))
    end
    return list_staff
  end

  def get_list_option_id
    list_id = Array.new()
    self.option.each do |option|
      list_id.push(option.id)
    end
    return list_id
  end

  def self.destroy(poll_id)
    poll = Poll.find(poll_id)
    poll.option.destroy
    poll.destroy
    poll.staff_polls.destroy
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
  	@polls = Poll.paginate(page: params[:page])
  end

  def show
    @poll = Poll.find(params[:id])
    @options = @poll.option
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.create!(
      id: Poll.last.id + 1,
      content: params[:poll][:content],
      staff_id: session[:user_id],
      created_at: "",
      updated_at: ""
    )
    redirect_to(@poll)
  end

  def update
    @poll = Poll.find(params[:id])
    if  params[:poll]
      checked_options = params[:poll][:options].values
      checked_options = checked_options.map(&:to_i)
      if params[:commit] == 'Vote'
        vote(@poll, checked_options)
      elsif params[:commit] == 'Delete'
        delete_option(@poll,checked_options)
      end
      redirect_to(@poll)
    else
      flash[:warning] = "0 option is selected"
      redirect_to(@poll)
    end
  end

  def vote(poll, checked_options)
    checked_options.each do |option_id|
      unless StaffPoll.exist(session[:user_id], option_id)
        StaffPoll.create(session[:user_id], poll.id, option_id)
      end
    end
    unchecked_options = poll.get_list_option_id - checked_options
    unchecked_options.each do |option_id|
      if StaffPoll.exist(session[:user_id], option_id)
        StaffPoll.destroy(session[:user_id], poll.id, option_id)
      end
    end
  end

  def delete_option(poll, checked_options)
    checked_options.each do |option_id|
      Option.destroy(option_id)
      StaffPoll.destroy(option_id)
    end
  end

  def destroy
    poll_id = params[:poll_id]
    Poll.destroy(poll_id)
    redirect_to(:action => 'index')
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  def have_polls?
    Poll.all.size > 0
  end
end

app/views/polls/_poll.html.erb
<td width=60%>
  <%= link_to poll.content, poll %>
</td>
<td width=30%>
  <% author = Staff.find(poll.staff_id)%>
  <%= link_to author.name, author%>
</td>
<td width=10%>
  <% if current_staff.id == poll.staff_id && current_staff.actived %>
    <%= link_to "Delete", polls_destroy_path(:poll_id => poll.id) , class: "btn btn-primary" %>
  <% end %>
</td>

app/views/polls/index.html.erb
<% provide(:title, 'All Poll') %>
<h1>All Poll</h1>
  <% if current_staff%>
    <%= will_paginate%>
    <table width=100%>
      <% @polls.each do |poll|%>
        <tr>
          <%= render poll%>
        </tr>
      <% end %>
    </table>
    <%= will_paginate%>
    <%= form_tag("/polls/new", method: "get") do %>
      <%= submit_tag("Add") %>
    <% end %>
	<% else %>
  	<%= link_to "Sign in now!", "/auth/google_oauth2" , id: "sign_in", class: "btn btn-lg btn-primary" %>
  <% end %>

app/views/polls/new.html.erb
<h1>Add new poll</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @poll, url: {action: "create"}, method: "post" do |f| %>
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </br>
      <%= f.submit "Submit", class: "btn btn-primary" %>

      <%= link_to "Cancel", "polls_index" , class: "btn btn-link" %>
    <% end %>

  </div>
</div>

app/views/polls/show.html.erb
<h1>Author: <%=Staff.find(@poll.staff_id).name%></h1>
<h2><%= @poll.content %></h2>
<% session[:poll_id] = @poll.id%>
<%= form_for @poll, url:{action: "update"}, method:"put" do |f|%>
<table width=100%>
  <tr>
    <td width=50%>
      Option
    </td>
    <td width=20%>
      score
    </td>
    <td width=30%>
      staff
    </td>
  </tr>
  <% @options.each_with_index do |option, index| %>
    <tr>
      <%= render option, index: index %>
    </tr>
  <% end %>
</table>
  <% if current_staff.actived%>
    <%= f.submit "Vote", class: "btn btn-primary"%>
    <%= f.submit "Delete", class: "btn btn-primary"%>
    <% if @poll.staff_id == current_staff.id%>
    <%= link_to "Add", new_option_path(:poll_id => @poll.id), class: "btn btn-primary" %>
    <% end %>
  <% end %>
<% end %>

app/views/polls/update.html.erb
<h1>Polls#update</h1>
<p>Find me in app/views/polls/update.html.erb</p>