config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#home"

  resources :sessions, only: [:create, :destroy]
  resources :static_pages, only: [:home]
  resources :staffs
  resources :polls
  resources :options

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy'

  get 'static_pages_home', to: 'static_pages#home'

  get 'staff_edit', to: 'staffs#edit'
  get 'staff_login', to: 'staffs#login'
  # get 'staff_show', to: 'staffs#show'
  # get 'staff_index', to: 'staffs#index'

  # get 'poll_new', to: 'polls#new'
  # post 'poll_create', to: 'polls#create'
  # get 'poll_show', to: 'polls#show'
  # get 'poll_update', to: 'polls#update'
  # get 'polls_index', to: 'polls#index'
  get 'polls_destroy', to: 'polls#destroy'

  get 'update_key_person_staff', to:'staffs#update_key_person'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://localhost:3000">Ladder Poll</a>
    by <a href="http://www.vccloud.vn/">VCCloud</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li>
            <%= link_to "Poll", polls_path %>
          </li>
          <li>
            <%= link_to "Staff", staffs_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= @current_staff.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", @current_staff %></li>
              <li><%= link_to "Settings", staff_edit_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path %>
              </li>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", staff_login_path, class: "btn btn-primary"%>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LadderPollTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<%= render 'layouts/header' %>
 <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
 <div class="container">
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>